import { Button, VerticalBox, LineEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    out property <string> secret_word <=> secret_input.text;
    out property <string> guessed_letter <=> guess_input.text;
    in-out property <string> solved_word <=> solved_secret.text;
    in property <int> user_errors;

    callback player1-finished();
    callback player2-guess();

    player1_view := VerticalBox {
        visible: true;
        HorizontalBox {
            secret_input := LineEdit {
                input-type: secret_visibility.pressed ? text : password;
                placeholder-text: "Enter text here";
            }
            secret_visibility := Button {
                text: "Visibility";
            }
        }

        Button {
            text: "Start Guessing";
            clicked => {
                root.player1-finished();
                player1_view.visible = false;
                player2_view.visible = true;
            }
        }
    }

    player2_view := VerticalBox {
        visible: false;
        solved_secret := LineEdit {
            enabled: false;
        }
        errors_counter := Text {
            text: "Errors: " + root.user_errors;
        }
        guess_input := LineEdit {
            input-type: text;
            placeholder-text: "Guess a letter";
        }
        Button {
            text: "Submit Guess";
            enabled: !guess_input.text.is-empty;
            clicked => {
                root.player2-guess();
                guess_input.text = "";
            }
        }
    }
}