import { Button, VerticalBox, LineEdit, HorizontalBox } from "std-widgets.slint";

export enum GameState { setup, play, finish}

export component AppWindow inherits Window {
    out property <string> secret_word <=> secret_input.text;
    out property <string> guessed_letter <=> guess_input.text;
    in-out property <string> solved_word <=> solved_secret.text;
    in property <int> user_errors;
    in property <bool> game_finished;
    in property <bool> game_lost;
    in-out property <GameState> state: setup;

    property<image> image_path: {
        if user_errors == 0 {
            return @image-url("../assets/start.png");
        } else if user_errors == 1 {
            return @image-url("../assets/error_01.png");
        } else if user_errors == 2 {
            return @image-url("../assets/error_02.png");
        } else if user_errors == 3 {
            return @image-url("../assets/error_03.png");
        } else if user_errors == 4 {
            return @image-url("../assets/error_last.png");
        } else if user_errors == 5 {
            return @image-url("../assets/dead.png");
        } else {
            return @image-url("../assets/error.png"); // fallback
        }
    }

    callback player1-finished();
    callback player2-guess();

    forward-focus: secret_input;

    VerticalBox {
        visible: root.state == GameState.setup;
        HorizontalBox {
            secret_input := LineEdit {
                input-type: secret_visibility.pressed ? text : password;
                placeholder-text: "Enter text here";
                accepted(text) => {
                    root.player1-finished();
                    root.state = GameState.play;
                }
                
            }
            secret_visibility := Button {
                text: "Visibility";
            }
        }

        Button {
            text: "Start Guessing";
            clicked => {
                root.player1-finished();
                root.state = GameState.play;
                guess_input.focus();
            }
        }
    }

    HorizontalBox {
        visible: root.state == GameState.play || root.state == GameState.finish;
        forward-focus: guess_input;
        Image {
            source: root.image_path;
            width: 50%;
            height: 100%;
        }
        VerticalBox {
            forward-focus: guess_input;
            
            solved_secret := LineEdit {
                enabled: false;
            }
            errors_counter := Text {
                text: "Errors: " + root.user_errors;
            }
            guess_input := LineEdit {
                input-type: text;
                placeholder-text: "Guess a letter";
                accepted(text) => {
                    root.player2-guess();
                    guess_input.text = "";
                    if root.game_finished {
                        root.state = GameState.finish
                    }
                }
            }
            Button {
                text: "Submit Guess";
                enabled: !guess_input.text.is-empty;
                clicked => {
                    root.player2-guess();
                    guess_input.text = "";
                    if root.game_finished {
                        root.state = GameState.finish
                    }
                }
            }
        }
    }
}