import { Button, VerticalBox, LineEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    out property <string> secret_word <=> secret_input.text;
    out property <string> guessed_letter: "";
    in property <string> solved_word: "";

    callback start-guessing();

    VerticalBox {
        HorizontalBox {
            secret_input := LineEdit {
                input-type: secret_visibility.pressed ? text : password;
                placeholder-text: "Enter text here";
            }
            secret_visibility := Button {
                text: "Visibility";
            }
        }

        Button {
            text: "Start Guessing";
            clicked => {
                root.start-guessing();
            }
        }
    }
}